USE [master]
GO

/****** Object:  Database [Enterprise]    Script Date: 30.03.2022 17:55:57 ******/
CREATE DATABASE [Enterprise]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Enterprise', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Enterprise.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Enterprise_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Enterprise_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Enterprise].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Enterprise] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Enterprise] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Enterprise] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Enterprise] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Enterprise] SET ARITHABORT OFF 
GO

ALTER DATABASE [Enterprise] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Enterprise] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Enterprise] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Enterprise] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Enterprise] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Enterprise] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Enterprise] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Enterprise] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Enterprise] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Enterprise] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Enterprise] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Enterprise] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Enterprise] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Enterprise] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Enterprise] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Enterprise] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Enterprise] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Enterprise] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Enterprise] SET  MULTI_USER 
GO

ALTER DATABASE [Enterprise] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Enterprise] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Enterprise] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Enterprise] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Enterprise] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Enterprise] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Enterprise] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Enterprise] SET  READ_WRITE 
GO

